version: "3.8"
services:
  backend:
    build: ./backend
    image: chatbot-backend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot
    networks:
      - chatbot_net

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - chatbot_net

networks:
  chatbot_net:
    driver: overlay

volumes:
  mongo-data:

